### ISSUE TITLE
Can't make new chatroom we using private static variables for it

### ISSUE THREAD

**Issue by kevintrancs** [amurphybeach/eggshell#8]
Rip

@dlom

**Comment by dlom** [comment]
Somehow, you managed to lose code that was commited and pushed to github.  I'm actually stupified as to how you managed to do so.  

I pulled the commits out of the aether and have reattached them to the master branch.  You're welcome.

**Comment by dlom** [comment]
Please never ever ever ever force push to github, or push without pulling beforehand @kevintrancs @kevintrancs @kevintrancs :shipit: :shipit: :shipit:
